[package]
name = "hwlender"
version = "0.1.0"
authors = ["Alex Hunt <alex.s.hunt7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
serde = "1"
serde_yaml = "0.8"
